version: "3.8"

services:
  matcha_world:
    build: .
    container_name: matcha_world_container
    image: matcha_world
    ports:
      - "916:916"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true      
    read_only: true                         # protect root file system
    cap_drop:
      - ALL
    volumes:
      # Persist uploads (only writable area in container)
      - ./src/app/uploads:/app/app/uploads 
      # IMPORTANT: bind the real flag into container root as read-only
      - ./src/flag.txt:/flag.txt:ro
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
